Create login route
GSG-G11/Quizzer pull request #40
Opened 2022-04-23 10:09 UTC by khaled-samy

### Solves  #16 
- created login validation
- created login controller

2022-04-23 11:29 UTC, zaher-aa requested changes

2022-04-23 11:29 UTC, zaher-aa commented on server/controllers/auth/login.ts
> +      .json({ data: user, message: 'User Log in Successfully' });
Status code for creating a new token is 201
```suggestion
    res
      .status(201)
      .cookie('token', token)
      .json({ data: user, message: 'User Log in Successfully' });
```

2022-04-23 11:29 UTC, zaher-aa commented on server/controllers/auth/login.ts
> +    const token = await signToken({ email, role });
The token should have user's id, name and role
```suggestion
    const token = await signToken({ userId, username, role });
```

2022-04-24 07:46 UTC, amjed-98 commented on server/controllers/auth/login.ts
> +      .status(201)
status should be 200

2022-04-24 07:47 UTC, amjed-98 requested changes
status should be 200
![image](https://user-images.githubusercontent.com/78312641/164966000-9dfe5f94-1c87-457f-87c5-3a4ec3354539.png)

2022-04-24 10:57 UTC, Mu7ammadAbed commented on server/controllers/auth/login.ts
> +    if (!isPasswordMatch) throw new CustomError('Your password is incorrect', 401);
```suggestion
    if (!isPasswordMatch) throw new CustomError('Incorrect email or password', 401);
```

2022-04-24 10:57 UTC, Mu7ammadAbed commented on server/controllers/auth/login.ts
> +    if (!isEmailTaken) throw new CustomError('Your email is incorrect', 401);
```suggestion
    if (!isEmailTaken) throw new CustomError('Incorrect email or password', 401);
```

2022-04-24 11:01 UTC, Mu7ammadAbed commented on server/controllers/auth/login.ts
> +      .cookie('token', token)
```suggestion
      .cookie('token', token, {
        httpOnly: true,
        secure: process.env.NODE_ENV === 'production',
      })
```

2022-04-24 11:10 UTC, Mu7ammadAbed approved these changes

2022-04-24 11:11 UTC, zaher-aa approved these changes

2022-04-24 11:12 UTC, amjed-98 approved these changes
great job

2022-04-24 11:13 UTC, merged