store user private score and send email
GSG-G11/Quizzer pull request #41
Opened 2022-04-23 11:09 UTC by zaher-aa

# Solves #38
- add students to the `scores` table when submitting a private test.
- send email to students when submitting private tests

2022-04-23 12:33 UTC, khaled-samy requested changes
check!

2022-04-23 12:33 UTC, khaled-samy commented on server/routes/student/index.ts
> +router.post('/score', checkAuth('student'), checkUserAttendQuiz, addPrivateQuizScore, sendEmail);
checUserAttendQuiz controller, should be in route `router.get('/quiz-data/:quizId', checUserAttendQuiz, quizDetails')`
so the user he can know before start the exam that he submitted it

2022-04-23 17:59 UTC, khaled-samy approved these changes

2022-04-25 03:21 UTC, Mu7ammadAbed approved these changes

2022-04-25 04:13 UTC, Mu7ammadAbed submitted a review, later dismissed

2022-04-25 05:21 UTC, khaled-samy approved these changes

2022-04-25 09:43 UTC, amjed-98 approved these changes

2022-04-25 10:30 UTC, khaled-samy approved these changes

2022-04-25 12:13 UTC, merged