convert to ts
GSG-G11/Quizzer pull request #75
Opened 2022-05-07 17:03 UTC by zaher-aa

### converted client file structure to typescript

2022-05-07 17:05 UTC, khaled-samy submitted a review, later dismissed

2022-05-08 02:30 UTC, amjed-98 requested changes

2022-05-08 02:30 UTC, amjed-98 commented on client/package.json
> +    "@types/jest": "^27.5.0",
shouldn't this be listed in devDependencies? 
in most cases anything that relates to typescript should be listed in devDependencies.

this article should help you decide:
https://stackoverflow.com/questions/45176661/how-do-i-decide-whether-types-goes-into-dependencies-or-devdependencies

2022-05-08 02:30 UTC, amjed-98 commented on client/package.json
> +    "@types/node": "^16.11.33",
do you really need @types/node? , because we are working on the browser here

2022-05-08 02:30 UTC, amjed-98 commented on client/package.json
> +    "styled-components": "^5.3.5",
do we really need this? I think material UI is enough, what do you think?

2022-05-08 02:41 UTC, amjed-98 requested changes

2022-05-08 02:41 UTC, amjed-98 commented on client/.gitignore
> +yarn-error.log*
maybe just ignore the files we actually have

2022-05-08 10:58 UTC, khaled-samy approved these changes

2022-05-08 10:59 UTC, amjed-98 approved these changes

2022-05-08 11:00 UTC, Mu7ammadAbed approved these changes

2022-05-08 11:01 UTC, merged